stages:
  - lint
  - test
  - weekly_tests

variables:
  EO_CONTAINERS: $REGISTRY_GITLAB/eo-containers
  EOREADER_CHANGES: eoreader/**/[^_]*.{py,xml}

include:
  - project: 'sertit/groupware'
    file: '/ci_templates/lint_3_10.yaml'
  - project: 'sertit/groupware'
    file: '/ci_templates/pytest.yaml'

.rules_pytest:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - changes:
        - $EOREADER_CHANGES
        - ci/**/*.{py,xml}
        - .gitlab-ci.yml

.pytest_tags:
  tags:
    - sertit
    - linux
    - high_memory

pytest:
  image: $EO_CONTAINERS:geo_latest
  extends:
    - .pytest
    - .rules_pytest
    - .pytest_tags
  variables:
    CI_EOREADER_USE_S3: "0"
    EOREADER_USE_DASK: "1"
    PATH_TO_TEST: ci/on_push
    COV: eoreader

pytest_s3:
  image: $EO_CONTAINERS:geo_latest
  extends:
    - .pytest
    - .rules_pytest
    - .pytest_tags
  variables:
    CI_EOREADER_USE_S3: "1"
    EOREADER_USE_DASK: "1"
    PATH_TO_TEST: ci/on_push
    COV: eoreader

pytest_end_to_end:
  image: $EO_CONTAINERS:geo_latest
  extends:
    - .pytest
    - .pytest_tags
  variables:
    CI_EOREADER_USE_S3: "0"
    EOREADER_USE_DASK: "1"
    PATH_TO_TEST: ci/weekly
    COV: eoreader
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "END_TO_END"'
      when: always
    - if: $CI_COMMIT_TAG
      when: always

pytest_end_to_end_314:
  image: $EO_CONTAINERS:geo_314_latest
  extends:
    - .pytest
    - .pytest_tags
  variables:
    CI_EOREADER_USE_S3: "0"
    EOREADER_USE_DASK: "1"
    PATH_TO_TEST: ci/weekly
    COV: eoreader
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "3.14"'
      when: always

pytest_no_dask:
  image: $EO_CONTAINERS:geo_latest
  extends:
    - .pytest
    - .pytest_tags
  variables:
    CI_EOREADER_USE_S3: "0"
    EOREADER_USE_DASK: "0"
    PATH_TO_TEST: ci/on_push
    COV: eoreader
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "NO_DASK"'
      when: always
    - if: $CI_COMMIT_TAG
      when: always

pytest_s3_no_dask:
  image: $EO_CONTAINERS:geo_latest
  extends:
    - .pytest
    - .pytest_tags
  variables:
    CI_EOREADER_USE_S3: "1"
    EOREADER_USE_DASK: "0"
    PATH_TO_TEST: ci/on_push
    COV: eoreader
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "NO_DASK"'
      when: always
    - if: $CI_COMMIT_TAG
      when: always
